### ISSUE TITLE
catkin_make failed while building calc_cost.cu

### ISSUE THREAD

**Issue by David-Willo** [dvorak0/VI-MEAN#13]
I just put the source code in the catkin workspace and try to build it using catkin_make command.
However, it failed with the following message：

> [ 54%] Built target std_msgs_generate_messages_py
> [ 55%] Building NVCC (Device) object VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/src/stereo_mapper_generated_calc_cost.cu.o
> [ 55%] Built target sensor_msgs_generate_messages_py
> [ 55%] Built target geometry_msgs_generate_messages_py
> [ 55%] Built target std_msgs_generate_messages_nodejs
> [ 55%] Built target geometry_msgs_generate_messages_nodejs
> [ 55%] Built target sensor_msgs_generate_messages_nodejs
> [ 60%] Built target chisel_ros_generate_messages_lisp
> CMake Error at stereo_mapper_generated_calc_cost.cu.o.cmake:207 (message):
>   Error generating
>   /home/davidwillo/Documents/catkin_ws/build/VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/src/./stereo_mapper_generated_calc_cost.cu.o
> 
> 
> VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/build.make:63: recipe for target 'VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/src/stereo_mapper_generated_calc_cost.cu.o' failed
> make[2]: *** [VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/src/stereo_mapper_generated_calc_cost.cu.o] Error 1
> CMakeFiles/Makefile2:2619: recipe for target 'VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/all' failed
> make[1]: *** [VI-MEAN/stereo_mapper/CMakeFiles/stereo_mapper.dir/all] Error 2

But there isn't any error message so I am confused about what's going on.
Can someone tell me where the problem can probably be?

**Comment by edgar-explorer** [comment]
@David-Willo  Have you solved this problem?

**Comment by shermes91** [comment]
I have the same problem. Any solutions here?
