### ISSUE TITLE
where to get camera_synchronizer node?

### ISSUE THREAD

**Issue by mylxiaoyi** [dvorak0/VI-MEAN#6]
Firstly thanks for sharing the amazing work.

I tried to test on euroc dataset, but i found that the launch script need camera_synchronizer node, where can i get the camera_synchronizer node? I searched through google, but got just pr2_camera_synchronizer, also i tried under indigo in mint 17.3 and used aptitude to search, but got nothing.

So where to get camera_synchronizer node? thanks!

PS:
os: mint 17.3
ros: indigo

**Comment by dvorak0** [comment]
It's our internal node. The only task of the node is to combine two images into one. And do you mean other launch files instead of sample.launch? Those scripts are used before but not maintained any more.

**Comment by mylxiaoyi** [comment]
Hi @dvorak0 , thanks for your reply.

I have tried sample_all.launch,  the result is perfect. I want to test dense mapping on euroc dataset, so i write a launch script under stereo_mapper named euroc_all.launch, and the content is as following:

```
<launch>
    <node name="rvizvisualisation" pkg="rviz" type="rviz" output="log" args="-d $(find self_calibration_estimator)/config/sample.rviz" />
    <include file="$(find chisel_ros)/launch/euroc.launch"/>
    <include file="$(find stereo_mapper)/launch/euroc.launch"/>
    <include file="$(find self_calibration_estimator)/launch/mapping/lin.launch"/>
</launch>
```
I noticed that chisel_ros/launch/euroc.launch and stereo_mapper/launch/euroc.launch existed, so i used them directly.

The script file self_calibration_estimator/launch/mapping/lin.launch needs camera_synchronizer node. I commented out camera_synchronizer, and made feature_tracker to subscribe topic /cam1/image_raw,

```
<node name="feature_tracker" pkg="feature_tracker" type="feature_tracker" output="log">
        <param name="calib_dir" type="string" value="$(find feature_tracker)/config/" />
        <param name="cam_name0" type="string" value="lin3_0" />
        <param name="cam_name1" type="string" value="lin3_1" />
        <param name="max_cnt" type="int" value="100" />
        <param name="min_dist" type="int" value="30" />
        <param name="window_size" type="int" value="20" />
        <param name="freq" type="int" value="2" />
        <param name="F_threshold" type="double" value="1.0" />
        <param name="T_threshold" type="double" value="0.5" />
        <param name="show_track" type="bool" value="true" />
        <param name="stereo_track" type="bool" value="false" />
        <param name="use_T" type="bool" value="false" />
        <param name="use_F" type="bool" value="true" />
        <param name="equalize" type="bool" value="true" />
        <remap from="~imu" to="/imu0" />
        <!--<remap from="~raw_image" to="/camera_synchronizer/image" />-->
        <remap from="~raw_image" to="/cam1/image_raw"/>
    </node>
```
I tested it with MH_05_difficult.bag, and i can get the estimated uav trajectory, but can not get dense mapping.  MH_05_difficult.bag is not suitable for dense mapping ? or there are something wrong with my operation ?

Thanks.

**Comment by dvorak0** [comment]
Use rqt_graph to check whether the pipeline of data is correct. See stereo_mapper's output to checkout what is happening there.

**Comment by mylxiaoyi** [comment]
Thanks, I will have a try.

**Comment by David-Willo** [comment]
@mylxiaoyi Hi, can you share your final launch script for running euroc dataset? Is your trajectory displayed in rviz correct by just using the euroc_all.launch you shown above?  Thanks!
----------------------
@dvorak0 Hi, If I want to run my own data, should I just calibrate my camera and provide an calibration file like sample_camera_calib.yaml and then modify the topic name and run the sample_all.launch directly or should I modify any parameter in self_calibration_estimator/launch/mapping/sample.launch? I test with euroc dataset and modify some parameter in those files but still cannot get a correct trajectory .
