### ISSUE TITLE
Missing checkers in IMU Factor

### ISSUE THREAD

**Issue by K0stIa** [dvorak0/VI-MEAN#7]
Would it be possible for you to provide this checkers?
https://github.com/dvorak0/VI-MEAN/blob/release/self_calibration_estimator/src/imu_factor.h#L193

-K.

**Comment by dvorak0** [comment]
That is only simply a gradient checker with numerical derivatives, mainly for debugging purpose.
Check the example in ProjectionFactor::check, and you could have your own check function.

**Comment by K0stIa** [comment]
Dont you have this function by any chance?

**Comment by K0stIa** [comment]
I am curiois to see your implementation.

**Comment by dvorak0** [comment]
Can't find that piece of code. Sorry for that.

**Comment by K0stIa** [comment]
what about your local git history? Why I am asking is that something you there is bad values of jaccobians components over biasses...
