### ISSUE TITLE
what does Utility::Qleft do?

### ISSUE THREAD

**Issue by K0stIa** [dvorak0/VI-MEAN#9]
Could you explain what does this function do?

https://github.com/dvorak0/VI-MEAN/blob/release/self_calibration_estimator/src/utility.h#L47

**Comment by dvorak0** [comment]
Quaternion multiplication has equivalent matrix form: q x b = Qleft(q)p = Qright(p)q.

Here are details: https://github.com/dvorak0/VI-MEAN/blob/release/support/notes/Appendix.pdf
